name: Assign triage label for new issues

on:
  issues:
    types: [opened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Assign triage label
      uses: andymckay/labeler@1.0.2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        add-labels: triage 
        ignore-if-assigned: true
